#!/bin/bash


currentpath=$(pwd)
if [[ ${currentpath} != *"Clinometer"* ]];then
	# currentpath does not contain "Clinometer"
	echo Clinometer Project Folder not found, exiting...
	exit 1
fi

clinometerpath="${currentpath%Clinometer*}Clinometer/"
echo "Project Folder: ${clinometerpath}"
cd ${clinometerpath}



# Read the versionName from gradle file

ver=$(grep -n "versionName " ./app/build.gradle | cut -d"'" -f 2)

if [ -z "$ver" ]; then
	echo Version number not found, exiting...
	exit 1
fi
echo "Preparing Clinometer v${ver}:"

apkrelease="apk/Clinometer-${ver}.apk"
apklatest="apk/Clinometer-latest.apk"
zipsource="sourcecode/Clinometer-${ver} - Source.zip"



# 1) Copy the APK file (generated by Android Studio
#    with "Generate Signed Bundle / APK" command) into ./apk

cp ./app/release/app-release.apk "${apkrelease}"
echo "- Created:             ${apkrelease}"



# 2) Update the latest APK file

cp "${apkrelease}" "${apklatest}"
echo "- Updated:             ${apklatest}"



# 3) Zip the Source into ./sourcecode folder

zip -r "${zipsource}" ./app/src ./app/*.* > /dev/null 2>&1
echo "- Zipped source into:  ${zipsource}"
